[package]
name = "dictionarium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bzip2 = "0.4.3"
parse_wiki_text = "0.1.5"
# peg = "0.8.1"
